version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"

  api-server:
    image: api-server
    ports:
      - "5050:5050"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
